import { useState, useEffect, useRef } from 'react';
import clsx from 'clsx';
import { Server, Cloud, Zap } from 'lucide-react';

export default function InferenceModule() {
    const [engine, setEngine] = useState('cpu'); // cpu, llama, vllm
    const [output, setOutput] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [stats, setStats] = useState({ speed: '--', time: '--' });
    const consoleRef = useRef(null);

    const generate = () => {
        setIsGenerating(true);
        setOutput('');
        setStats({ speed: '--', time: '--' });

        let speed = 10; // chars per interval roughly mapped to tokens
        if (engine === 'llama') speed = 40;
        if (engine === 'vllm') speed = 150;

        const text = `Here is a poem about space coding:\n\nStars align in binary code,\nA cosmic script, a silent mode.\nWhile neurons fire in silicone,\nWe build new worlds, purely known.\n\n(Generated by ${engine.toUpperCase()})`;
        const chars = text.split('');
        let i = 0;
        const startTime = Date.now();

        const interval = setInterval(() => {
            if (i >= chars.length) {
                clearInterval(interval);
                setIsGenerating(false);
                const totalTime = ((Date.now() - startTime) / 1000).toFixed(2);
                setStats({
                    speed: `${speed} tok/s`,
                    time: `${totalTime}s`
                });
            } else {
                setOutput(prev => prev + chars[i]);
                i++;
                if (consoleRef.current) consoleRef.current.scrollTop = consoleRef.current.scrollHeight;
            }
        }, 1000 / speed); // Interval time
    };

    return (
        <div className="flex flex-col gap-6 animate-fade-in animate-slide-up">
            <div className="explainer-box">
                <div className="explainer-title">
                    <span className="bg-blue-600/20 text-blue-400 p-1 rounded mr-3 text-xs">MODULE 6</span>
                    Inference & Latency
                </div>
                <p className="explainer-text">
                    Simulates actual generation delay based on hardware choice. Compare Local CPU vs GPU vs Cloud.
                </p>
            </div>

            <div className="glass-panel p-6 rounded-xl">
                <div className="grid grid-cols-3 gap-4 mb-6">
                    {[
                        { id: 'cpu', name: 'Standard CPU', speed: '10 tok/s', icon: Server },
                        { id: 'llama', name: 'llama.cpp (Metal)', speed: '40 tok/s', icon: Zap },
                        { id: 'vllm', name: 'vLLM (H100 GPU)', speed: '150+ tok/s', icon: Cloud }
                    ].map((opt) => (
                        <button
                            key={opt.id}
                            onClick={() => setEngine(opt.id)}
                            className={clsx(
                                "flex flex-col items-center justify-center p-4 rounded border transition-all text-center gap-2",
                                engine === opt.id
                                    ? "bg-blue-600/20 border-blue-500 text-white shadow-[0_0_15px_rgba(59,130,246,0.3)]"
                                    : "bg-slate-800/50 border-slate-700 text-slate-400 hover:bg-slate-800"
                            )}>
                            <opt.icon className="w-6 h-6 mb-1" />
                            <div className="font-bold text-sm">{opt.name}</div>
                            <div className="text-xs opacity-70">{opt.speed}</div>
                        </button>
                    ))}
                </div>

                <div className="mb-4">
                    <textarea
                        readOnly
                        value="Write a short poem about coding in space."
                        className="w-full bg-slate-900 text-slate-300 p-3 rounded border border-slate-700 outline-none focus:border-slate-500 cursor-not-allowed"
                    />
                </div>

                <button
                    onClick={generate}
                    disabled={isGenerating}
                    className="btn-primary w-full py-3 rounded text-white font-bold disabled:opacity-50 mb-6"
                >
                    {isGenerating ? "Generating..." : "Run Inference"}
                </button>

                <div
                    ref={consoleRef}
                    className="bg-black p-4 rounded text-green-400 h-40 overflow-auto whitespace-pre-wrap font-mono text-sm leading-relaxed border border-slate-800 shadow-inner"
                >
                    {output}
                    <span className="w-2 h-4 bg-green-400 inline-block ml-1 animate-pulse align-middle"></span>
                </div>

                <div className="flex justify-between mt-4 text-center px-10">
                    <div>
                        <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">Speed</div>
                        <div className="text-xl font-bold text-white">{stats.speed}</div>
                    </div>
                    <div>
                        <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">Total Time</div>
                        <div className="text-xl font-bold text-white">{stats.time}</div>
                    </div>
                </div>
            </div>
        </div>
    );
}
